In [ ]:
#checking numpy version
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
#printing elements of an array
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [ ]:
#slicing an array
arr=np.array([[1,2,3],[4,5,7]])
print(arr[[0,1],1])

[2 5]


In [ ]:
# numpy copy
arr=np.array([[1,2,3],[4,5,7]])
x=arr.copy()
arr[1]=45
print(arr)
print(x)


[[ 1  2  3]
 [45 45 45]]
[[1 2 3]
 [4 5 7]]


In [ ]:
#numpy view
arr=np.array([[1,2,3],[4,5,7]])
y=arr.view()
arr[0,2]=81
print(arr)
print(y)

[[ 1  2 81]
 [ 4  5  7]]
[[ 1  2 81]
 [ 4  5  7]]


In [ ]:
#checking data type
arr=np.array([[1,2,3],[4,5,7]])
print(arr.dtype)

int64


In [ ]:
#array indexing
arr=np.array([1,2,3,5,7,8,9])
print(arr[::])
print(arr[0:4])
print(arr[-4:-1:2])

[1 2 3 5 7 8 9]
[1 2 3 5]
[5 8]


In [ ]:
#checking array dimension
arr=np.array([[1,2,3],[4,5,7]])
print(arr.ndim)

2


In [ ]:
# array shape
arr=np.array([[1,2,3],[4,5,7]])
print(arr.shape)

(2, 3)


In [ ]:
#Reshaping an array
arr=np.array([1,2,3,4,5,6,7,8,9,0,11,12])
new_arr=arr.reshape(4,3)
print(arr)
print(new_arr)

[ 1  2  3  4  5  6  7  8  9  0 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0 11 12]]
